### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by christianbender** [caesarleroux/Minx#1]
Hello,

I have found your repo on GitHub.
I written a simple assembler-like language in python. Like your language. See [here](https://github.com/christianbender/PythonAssembler)
How can I contribute?

PS: In the moment I building a [befunge-93](https://en.wikipedia.org/wiki/Befunge)  interpreter in Java.

greetings

Christian

**Comment by caesarleroux** [comment]
Hi! What would you like to contribute to Minx? :) You fork the repository, make the proposed changes to the project files, submit a pull request and wait for me to merge it! :)

**Comment by christianbender** [comment]
@caesarleroux  thanks for response

**Comment by christianbender** [comment]
@caesarleroux Has your language control structures? such as loops, or selections (if-else...)

**Comment by caesarleroux** [comment]
No, unfortunately it does not, I am stillgetting my head around the implementation of such features... Linear parsing is obviously not the mechanism I want.

**Comment by christianbender** [comment]
@caesarleroux little trick. save all recognized token in a list. Then you can easily implemented jump-commands for examples loops und selections.

**Comment by caesarleroux** [comment]
@christianbender Could you maybe show me this in a small example?

**Comment by caesarleroux** [comment]
@christianbender Could you maybe show me this in a small example?

**Comment by christianbender** [comment]
@caesarleroux 

imagine your scanner has get the following sequence.

```assembly
add eax, 45
```
The scanner recognizes the tokens  ```add```, ```eax``` and ```45```
The scanner pushes the tokens into a list. 

The token list looks like following.
```assembly
add
eax
45
```
Your parser goes through the list from the beginning. If you recognizes a label (for goto) your note the index.  If you will jump to a label then set equal your pointer (index) to the index of the certain label.

**detriment:** your need a token list. That waste memory space. 
**advantage:** You can simple implement parser and control structures.

These technic I used in my assembler like language.

**Comment by christianbender** [comment]
@caesarleroux 

We can work with python statement ```yield`` too. At the moment I experiment with the python lexa-generator ```shlex```. These module simplify the scanner construction!

**Comment by caesarleroux** [comment]
I still have a few questions, I'll get back to you soon about said questions. For now, I will merge your PR. Seems to work and seems to be useful and a good resource.

**Comment by christianbender** [comment]
We should use this module http://www.dabeaz.com/ply/ply.html 
With this module we can build a tokenizer for the MINX langauge. quiete simple!
